server:
  port: 8088
mqtt:
  port: 1883

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/goiot
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

